### ISSUE TITLE
HOME environment variable is not available when executing via API

### ISSUE THREAD

**Issue by serialh0bbyist** [reidmv/reidmv-taskplan#4]
When executing via the API the following error occurs:
```bash
  /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/puppetdb/config.rb:9:in `expand_path': couldn't find login name -- expanding `~' (ArgumentError)
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/puppetdb/config.rb:9:in `<class:Config>'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/puppetdb/config.rb:8:in `<module:PuppetDB>'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/puppetdb/config.rb:7:in `<module:Bolt>'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/puppetdb/config.rb:6:in `<top (required)>'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/puppetdb.rb:5:in `<top (required)>'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/cli.rb:18:in `<top (required)>'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/config.rb:8:in `<top (required)>'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt/executor.rb:11:in `<top (required)>'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt.rb:4:in `<module:Bolt>'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/lib/bolt.rb:3:in `<top (required)>'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/bolt-0.21.4/exe/bolt:4:in `<top (required)>'
  	from /opt/puppetlabs/puppet/bin/bolt:23:in `load'
  	from /opt/puppetlabs/puppet/bin/bolt:23:in `<main>'
```

The expand method fails due to not being able to resolve the `~` shortcut.

Pull request #3 fixes this issue by adding the `HOME` environment variable, and allowing users to specify additional environment variables if need be.

**Comment by reidmv** [comment]
I would love to resolve the HOME problem without exposing anything new to users, if we can. Are there other known use cases where it is necessary to set an environment variable in order to operate taskplan?

I've tried to address HOME specifically here: https://github.com/reidmv/reidmv-taskplan/blob/0.1.2/tasks/init.rb#L13-L18. If we don't know of specific use cases for it, my preference is to not expose the ability to configure other environment variables.

**Comment by serialh0bbyist** [comment]
I can't recall any other specific use cases at the moment.

**Comment by frizop** [comment]
I think this solves the use cases

**Comment by reidmv** [comment]
Awesome - thanks @as0bu @frizop. I'll close out these issues and PRs for now. Let me know if anything else comes up!
